{% set version = "6.2.4" %}

package:
  name: pysnmp
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pysnmp/pysnmp-{{ version }}.tar.gz
  sha256: 8b1346f561fdc53f13019c5ec2c108224b4935d5bb6d2c0133ca236bbae77665

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8,<4.0
    - pyasn1 >=0.4.8,!=0.5.0
    - pysmi >=1.3.0,<2.0.0
    - pysnmpcrypto >=0.0.4,<0.0.5

test:
  imports:
    - pysnmp
    - pysnmp.carrier
    - pysnmp.carrier.asyncio
    - pysnmp.carrier.asyncio.dgram
    - pysnmp.carrier.asyncore
    - pysnmp.carrier.asyncore.dgram
    - pysnmp.carrier.asynsock
    - pysnmp.carrier.asynsock.dgram
    - pysnmp.carrier.twisted
    - pysnmp.carrier.twisted.dgram
    - pysnmp.entity
    - pysnmp.entity.rfc3413
    - pysnmp.entity.rfc3413.oneliner
    - pysnmp.hlapi
    - pysnmp.hlapi.asyncio
    - pysnmp.hlapi.asyncore
    - pysnmp.hlapi.asyncore.sync
    - pysnmp.hlapi.asyncore.sync.compat
    - pysnmp.hlapi.twisted
    - pysnmp.proto
    - pysnmp.proto.acmod
    - pysnmp.proto.api
    - pysnmp.proto.mpmod
    - pysnmp.proto.proxy
    - pysnmp.proto.secmod
    - pysnmp.proto.secmod.eso
    - pysnmp.proto.secmod.eso.priv
    - pysnmp.proto.secmod.rfc3414
    - pysnmp.proto.secmod.rfc3414.auth
    - pysnmp.proto.secmod.rfc3414.priv
    - pysnmp.proto.secmod.rfc3826
    - pysnmp.proto.secmod.rfc3826.priv
    - pysnmp.proto.secmod.rfc7860
    - pysnmp.proto.secmod.rfc7860.auth
    - pysnmp.smi
    - pysnmp.smi.mibs
    - pysnmp.smi.mibs.instances

about:
  home: http://snmplabs.com/pysnmp
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: SNMP library for Python
  description: |
    PySNMP is a cross-platform, pure-Python SNMP engine implementation. It
    features fully-functional SNMP engine capable to act in Agent/Manager/Proxy
    roles, talking SNMP v1/v2c/v3 protocol versions over IPv4/IPv6 and other
    network transports.
  doc_url: http://pysnmp.sourceforge.net/docs/tutorial.html
  doc_source_url: https://github.com/etingof/pysnmp/tree/master/docs/source/docs
  dev_url: https://github.com/etingof/pysnmp

extra:
  recipe-maintainers:
    - nehaljwani
