{% set name = "pysnmp" %}
{% set version = "4.4.11" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "fe8bde566baea42e467ad55db028935cb3ac7243733b58ba25b1aa5b08f8fbec" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ file_ext }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  {{ hash_type }}: {{ hash_value }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pyasn1 >=0.2.3
    - pysmi
    - pycryptodomex
    - trollius
    - twisted

test:
  imports:
    - pysnmp
    - pysnmp.carrier
    - pysnmp.carrier.asyncio
    - pysnmp.carrier.asyncio.dgram
    - pysnmp.carrier.asyncore
    - pysnmp.carrier.asyncore.dgram
    - pysnmp.carrier.asynsock
    - pysnmp.carrier.asynsock.dgram
    - pysnmp.carrier.twisted
    - pysnmp.carrier.twisted.dgram
    - pysnmp.entity
    - pysnmp.entity.rfc3413
    - pysnmp.entity.rfc3413.oneliner
    - pysnmp.hlapi
    - pysnmp.hlapi.asyncio
    - pysnmp.hlapi.asyncore
    - pysnmp.hlapi.asyncore.sync
    - pysnmp.hlapi.asyncore.sync.compat
    - pysnmp.hlapi.twisted
    - pysnmp.proto
    - pysnmp.proto.acmod
    - pysnmp.proto.api
    - pysnmp.proto.mpmod
    - pysnmp.proto.proxy
    - pysnmp.proto.secmod
    - pysnmp.proto.secmod.eso
    - pysnmp.proto.secmod.eso.priv
    - pysnmp.proto.secmod.rfc3414
    - pysnmp.proto.secmod.rfc3414.auth
    - pysnmp.proto.secmod.rfc3414.priv
    - pysnmp.proto.secmod.rfc3826
    - pysnmp.proto.secmod.rfc3826.priv
    - pysnmp.proto.secmod.rfc7860
    - pysnmp.proto.secmod.rfc7860.auth
    - pysnmp.smi
    - pysnmp.smi.mibs
    - pysnmp.smi.mibs.instances

about:
  home: http://snmplabs.com/pysnmp
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: SNMP library for Python
  description: |
    PySNMP is a cross-platform, pure-Python SNMP engine implementation. It
    features fully-functional SNMP engine capable to act in Agent/Manager/Proxy
    roles, talking SNMP v1/v2c/v3 protocol versions over IPv4/IPv6 and other
    network transports.
  doc_url: http://pysnmp.sourceforge.net/docs/tutorial.html
  doc_source_url: https://github.com/etingof/pysnmp/tree/master/docs/source/docs
  dev_url: https://github.com/etingof/pysnmp

extra:
  recipe-maintainers:
    - nehaljwani
