{% set version = "7.1.18" %}

package:
  name: pysnmp
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pysnmp/pysnmp-{{ version }}.tar.gz
  sha256: c89f387bd071cf0efcc02b57afe92185bc0c53c1b9e70587b879f8a96bf51eb3

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<4.0
    - pyasn1 >=0.4.8,!=0.5.0
    - pysmi >=1.3.0,<2.0.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - pysnmp
    - pysnmp.carrier
    - pysnmp.carrier.asyncio
    - pysnmp.carrier.asyncio.dgram
    - pysnmp.entity
    - pysnmp.entity.rfc3413
    - pysnmp.hlapi.asyncio
    - pysnmp.proto
    - pysnmp.proto.acmod
    - pysnmp.proto.api
    - pysnmp.proto.mpmod
    - pysnmp.proto.proxy
    - pysnmp.proto.secmod
    - pysnmp.proto.secmod.eso
    - pysnmp.proto.secmod.eso.priv
    - pysnmp.proto.secmod.rfc3414
    - pysnmp.proto.secmod.rfc3414.auth
    - pysnmp.proto.secmod.rfc3414.priv
    - pysnmp.proto.secmod.rfc3826
    - pysnmp.proto.secmod.rfc3826.priv
    - pysnmp.proto.secmod.rfc7860
    - pysnmp.proto.secmod.rfc7860.auth
    - pysnmp.smi
    - pysnmp.smi.mibs
    - pysnmp.smi.mibs.instances

about:
  home: https://www.pysnmp.com
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: SNMP library for Python
  description: |
    PySNMP is a cross-platform, pure-Python SNMP engine implementation. It
    features fully-functional SNMP engine capable to act in Agent/Manager/Proxy
    roles, talking SNMP v1/v2c/v3 protocol versions over IPv4/IPv6 and other
    network transports.
  doc_url: https://docs.lextudio.com/pysnmp
  doc_source_url: https://github.com/lextudio/pysnmp/tree/main/docs/source/docs
  dev_url: https://github.com/lextudio/pysnmp

extra:
  recipe-maintainers:
    - nehaljwani
